# Generated by Django 5.2.1 on 2025-05-29 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_name', models.CharField(max_length=50)),
                ('prod_price', models.FloatField(default=0)),
                ('prod_image', models.ImageField(upload_to='avatars/')),
            ],
        ),
    ]
