# Generated by Django 5.2.1 on 2025-05-29 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productstore',
            name='category',
            field=models.CharField(choices=[('VEG', 'Овощи'), ('FRT', 'Фрукты'), ('JUS', 'Not working'), ('DFT', 'Not working'), ('unknown', 'Not stated')], default='unknown'),
        ),
    ]
