# Generated by Django 5.2.1 on 2025-05-29 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_productstore_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductStore',
            new_name='Product',
        ),
    ]
