# Generated by Django 4.2.7 on 2025-05-29 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_prod_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('VEG', 'Овощи'), ('FRT', 'Фрукты'), ('JUS', 'Соки'), ('DFT', 'Сухофрукты'), ('unknown', 'Not stated')], default='unknown', max_length=50),
        ),
    ]
