# Generated by Django 5.2.1 on 2025-05-30 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='prod_price',
            new_name='prod_new_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='prod_discount',
        ),
        migrations.AddField(
            model_name='product',
            name='prod_old_price',
            field=models.FloatField(default=0),
        ),
    ]
