# Generated by Django 5.2.1 on 2025-05-30 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_rename_prod_price_product_prod_new_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='availability',
            field=models.IntegerField(choices=[(1, 'в наличии'), (2, 'нет в наличии')], default=1),
        ),
    ]
