# Generated by Django 5.2.1 on 2025-05-30 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_product_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='availability',
            field=models.IntegerField(choices=[(1, 'в наличии'), (2, 'нет в наличии')], default='в наличии'),
        ),
    ]
