# Generated by Django 5.2.1 on 2025-05-30 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_product_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='availability',
            field=models.CharField(choices=[('в наличии', 'в наличии'), ('нет в наличии', 'нет в наличии')]),
        ),
    ]
