# Generated by Django 5.2.1 on 2025-05-15 08:15

import Shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0004_user_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[(1, 'Мужской'), (0, 'Женский'), ('None', 'Боевой верталет t43')], default=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(default=18, validators=[Shop.models.tri_ne_bolee]),
        ),
    ]
