# Generated by Django 5.2.1 on 2025-05-15 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0008_alter_product_type_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('1', 'Мужской'), ('0', 'Женский'), ('None', 'Боевой верталет t43')], default='None'),
        ),
    ]
