# Generated by Django 5.2.1 on 2025-05-16 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0009_alter_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default='2025-05-16'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('1', 'Алкоголь'), ('0', 'Еда'), ('2', 'Not Stated')], default=0, max_length=20),
        ),
        migrations.AddConstraint(
            model_name='cart',
            constraint=models.UniqueConstraint(fields=('user_id', 'product_id'), name='user_product'),
        ),
    ]
