# Generated by Django 5.2.1 on 2025-05-26 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0011_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('1', 'Мужской'), ('0', 'Женский'), ('None', 'Не указан')], default='None'),
        ),
    ]
