# Generated by Django 4.2.7 on 2025-05-27 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0012_alter_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('1', 'Мужской'), ('0', 'Женский'), ('None', 'Не указан')], default='None', max_length=50),
        ),
    ]
